---@meta

---This generates a unique GUID (Global Unique Identifier). This is almost certain to be unique throughout the world, and at any time (ie. completely and utterly unique).
---
---The GUID will look like this: `"6B29FC40-CA47-1067-B31D-00DD010662DA"`
---
---The purpose of this is to give you a way of having a unique identifier (eg. for a variable).
---
---These numbers may seem cumbersome, but at least if you use them you are guaranteed of a unique identifier. Contrast this to [`GetUniqueNumber`](lua://GetUniqueNumber) which only returns a unique number for this session. Thus, the numbers (from `GetUniqueNumber`) will not be unique over multiple sessions.
---
---Also, using random number generation for unique identifiers has a chance of returning the same number, depending on a) the seed given to the generator; and b) the way the generator must eventually recyle and regenerate the same sequence.
---@return string guid A 36-character GUID.
---
---@see GetUniqueID
---@see GetUniqueNumber
function CreateGUID() end

---This uses [`CreateGUID`](lua://CreateGUID) to get a unique number, and then hashes it, retaining 24 characters (96 bits) of the hash. This generates a nice, unique identifier, like this: `"0a96ce42d8e0ede554d3b9ab"`. The number generated here will be used by plugins to uniquely identify themselves.
---
---You could also use it for variable, trigger, timer, alias names, when generated by a script, to ensure uniqueness over multiple sessions. You could also use it as a handy "password generator", as the number sequences are hardly going to be predicable.
---
---Contrast this to [`GetUniqueNumber`](lua://GetUniqueNumber) which only returns a unique number for this session. Thus, the numbers (from `GetUniqueNumber`) will not be unique over multiple sessions.
---
---Also, using random number generation for unique identifiers has a chance of returning the same number, depending on a) the seed given to the generator; and b) the way the generator must eventually recyle and regenerate the same sequence.
---@return string id A 24-character unique identifier.
---
---@see CreateGUID
---@see GetUniqueNumber
function GetUniqueID() end

---Generates a unique integer in the range 0 to 9,223,372,036,854,775,807.
---
---This number will be unique for this session, across all worlds. You might use it to generate unique labels for one-shot timers, or other similar purposes.
---
---Note that the number will eventually "wrap around" and thus, if you generate a lot of them (ie. 9,223,372,036,854,775,807), they will no longer be unique. That said, 9 quintillion is a lot!
---
---Also note that the numbers generated will not necessarily be in sequence.
---
---**Important:** this number is reset for each new session, so these numbers are only unique per session, not indefinitely.
---@return integer number A unique integer in the range 0 to 9,223,372,036,854,775,807.
---
---@see CreateGUID
---@see GetUniqueID
function GetUniqueNumber() end

---Alias for [`utils.hash`](lua://utils.hash).
---@param text string
---@return string hex 40-character hex string.
function Hash(text) end

---This function provides an interface to the internal routine used to convert trigger and alias "simple" wildcard expressions to full regular expressions.
---
---Example:
---
---```lua
---print(MakeRegularExpression("* goes *"))
---```
---
---Output: `"^(.*?) goes (.*?)$"`
---
---The behaviour is basically:
---
---* Put ^ at the start of the expression
---* Put $ at the end of the expression
---* Convert each occurrence of "*" to "(.*?)"
---* Non-printable characters in the range 0x00 to 0x1F become hex sequences
---* Non alphanumeric characters are escaped with a backslash.
---@param text string
---@return string regex The original string converted to a regular expression.
function MakeRegularExpression(text) end
