use std::path::PathBuf;

use mud_transformer::UseMxp;
use mud_transformer::mxp::RgbColor;
use serde::Deserialize;
use smushclient_plugins::{Alias, CursorVec, Timer, Trigger};

use super::super::types::*;

#[derive(Deserialize)]
pub struct World {
    // Connecting
    pub name: String,
    pub site: String,
    pub port: u16,
    pub use_proxy: bool,
    pub proxy_server: String,
    pub proxy_port: u16,
    pub proxy_username: String,
    pub proxy_password: String,
    pub save_world_automatically: bool,

    // Login
    pub player: String,
    pub password: String,
    pub connect_method: AutoConnect,
    pub connect_text: String,

    // Logging
    pub log_file_preamble: String,
    pub log_file_postamble: String,
    pub log_format: LogFormat,
    pub log_in_colour: bool,
    pub log_output: bool,
    pub log_input: bool,
    pub log_notes: bool,
    pub log_mode: LogMode,
    pub auto_log_file_name: Option<String>,
    pub write_world_name_to_log: bool,
    pub log_line_preamble_output: String,
    pub log_line_preamble_input: String,
    pub log_line_preamble_notes: String,
    pub log_line_postamble_output: String,
    pub log_line_postamble_input: String,
    pub log_line_postamble_notes: String,
    pub log_script_errors: bool,

    // Timers
    #[serde(serialize_with = "skip_temporary")]
    pub timers: CursorVec<Timer>,
    pub enable_timers: bool,

    // Output
    pub show_bold: bool,
    pub show_italic: bool,
    pub show_underline: bool,
    pub indent_paras: u8,
    pub ansi_colours: [RgbColor; 16],
    pub use_default_colours: bool,
    pub display_my_input: bool,
    pub echo_colour: Option<RgbColor>,
    pub echo_background_colour: Option<RgbColor>,
    pub keep_commands_on_same_line: bool,
    pub new_activity_sound: Option<String>,
    pub line_information: bool,

    // MUD
    pub use_mxp: UseMxp,
    pub ignore_mxp_colour_changes: bool,
    pub use_custom_link_colour: bool,
    pub hyperlink_colour: RgbColor,
    pub mud_can_change_link_colour: bool,
    pub underline_hyperlinks: bool,
    pub mud_can_remove_underline: bool,
    pub hyperlink_adds_to_command_history: bool,
    pub echo_hyperlink_in_output_window: bool,
    pub terminal_identification: String,
    pub disable_compression: bool,
    pub naws: bool,
    pub carriage_return_clears_line: bool,
    pub utf_8: bool,
    pub convert_ga_to_newline: bool,
    pub no_echo_off: bool,
    pub enable_command_stack: bool,
    pub command_stack_character: u8,
    pub mxp_debug_level: MXPDebugLevel,

    // Triggers
    #[serde(serialize_with = "skip_temporary")]
    pub triggers: CursorVec<Trigger>,
    pub enable_triggers: bool,
    pub enable_trigger_sounds: bool,

    // Aliases
    #[serde(serialize_with = "skip_temporary")]
    pub aliases: CursorVec<Alias>,
    pub enable_aliases: bool,

    // Keypad
    pub numpad_shortcuts: NumpadMapping,
    pub keypad_enable: bool,
    pub hotkey_adds_to_command_history: bool,
    pub echo_hotkey_in_output_window: bool,

    // Scripting
    pub enable_scripts: bool,
    pub world_script: Option<String>,
    pub script_reload_option: ScriptRecompile,
    pub note_text_colour: Option<RgbColor>,
    pub note_background_colour: Option<RgbColor>,
    pub script_errors_to_output_window: bool,
    pub error_text_colour: Option<RgbColor>,
    pub error_background_colour: Option<RgbColor>,

    // Hidden
    pub plugins: Vec<PathBuf>,
}

impl From<World> for super::super::World {
    fn from(value: World) -> Self {
        let World {
            name,
            site,
            port,
            use_proxy,
            proxy_server,
            proxy_port,
            proxy_username,
            proxy_password,
            save_world_automatically,
            player,
            password,
            connect_method,
            connect_text,
            log_file_preamble,
            log_file_postamble,
            log_format,
            log_in_colour,
            log_output,
            log_input,
            log_notes,
            log_mode,
            auto_log_file_name,
            write_world_name_to_log,
            log_line_preamble_output,
            log_line_preamble_input,
            log_line_preamble_notes,
            log_line_postamble_output,
            log_line_postamble_input,
            log_line_postamble_notes,
            log_script_errors,
            timers,
            enable_timers,
            show_bold,
            show_italic,
            show_underline,
            indent_paras,
            ansi_colours,
            use_default_colours,
            display_my_input,
            echo_colour,
            echo_background_colour,
            keep_commands_on_same_line,
            new_activity_sound,
            line_information,
            use_mxp,
            ignore_mxp_colour_changes,
            use_custom_link_colour,
            hyperlink_colour,
            mud_can_change_link_colour,
            underline_hyperlinks,
            mud_can_remove_underline,
            hyperlink_adds_to_command_history,
            echo_hyperlink_in_output_window,
            terminal_identification,
            disable_compression,
            naws,
            carriage_return_clears_line,
            utf_8,
            convert_ga_to_newline,
            no_echo_off,
            enable_command_stack,
            command_stack_character,
            mxp_debug_level,
            triggers,
            enable_triggers,
            enable_trigger_sounds,
            aliases,
            enable_aliases,
            numpad_shortcuts,
            keypad_enable,
            hotkey_adds_to_command_history,
            echo_hotkey_in_output_window,
            enable_scripts,
            world_script,
            script_reload_option,
            note_text_colour,
            note_background_colour,
            script_errors_to_output_window,
            error_text_colour,
            error_background_colour,
            plugins,
        } = value;

        Self {
            name,
            site,
            port,
            use_ssl: false,
            use_proxy,
            proxy_server,
            proxy_port,
            proxy_username,
            proxy_password,
            save_world_automatically,
            player,
            password,
            connect_method,
            connect_text,
            log_file_preamble,
            log_file_postamble,
            log_format,
            log_in_colour,
            log_output,
            log_input,
            log_notes,
            log_mode,
            auto_log_file_name,
            write_world_name_to_log,
            log_line_preamble_output,
            log_line_preamble_input,
            log_line_preamble_notes,
            log_line_postamble_output,
            log_line_postamble_input,
            log_line_postamble_notes,
            log_script_errors,
            timers,
            enable_timers,
            show_bold,
            show_italic,
            show_underline,
            indent_paras,
            ansi_colours,
            use_default_colours,
            display_my_input,
            echo_colour,
            echo_background_colour,
            keep_commands_on_same_line,
            new_activity_sound,
            line_information,
            use_mxp,
            ignore_mxp_colour_changes,
            use_custom_link_colour,
            hyperlink_colour,
            mud_can_change_link_colour,
            underline_hyperlinks,
            mud_can_remove_underline,
            hyperlink_adds_to_command_history,
            echo_hyperlink_in_output_window,
            terminal_identification,
            disable_compression,
            naws,
            carriage_return_clears_line,
            utf_8,
            convert_ga_to_newline,
            no_echo_off,
            enable_command_stack,
            command_stack_character,
            mxp_debug_level,
            triggers,
            enable_triggers,
            enable_trigger_sounds,
            aliases,
            enable_aliases,
            numpad_shortcuts,
            keypad_enable,
            hotkey_adds_to_command_history,
            echo_hotkey_in_output_window,
            enable_scripts,
            world_script,
            script_reload_option,
            note_text_colour,
            note_background_colour,
            script_errors_to_output_window,
            error_text_colour,
            error_background_colour,
            plugins,
        }
    }
}
