#include "globals.h"
#include "../miniwindow/miniwindow.h"
#include "../qlua.h"
#include "smushclient_qt/src/ffi/send_request.cxx.h"
#include <utility>
extern "C"
{
#include "lua.h"
}

struct TableEntry : std::pair<const char*, lua_Integer>
{
  template<typename T>
  constexpr TableEntry(const char* key, T value)
    : std::pair<const char*, lua_Integer>(key, static_cast<lua_Integer>(value))
  {
  }
};

static const TableEntry alias_flag[]{
  { "Enabled", AliasFlag::Enabled },
  { "KeepEvaluating", AliasFlag::KeepEvaluating },
  { "IgnoreAliasCase", AliasFlag::IgnoreAliasCase },
  { "OmitFromLogFile", AliasFlag::OmitFromLogFile },
  { "RegularExpression", AliasFlag::RegularExpression },
  { "ExpandVariables", AliasFlag::ExpandVariables },
  { "Replace", AliasFlag::Replace },
  { "AliasSpeedWalk", AliasFlag::AliasSpeedWalk },
  { "AliasQueue", AliasFlag::AliasQueue },
  { "AliasMenu", AliasFlag::AliasMenu },
  { "Temporary", AliasFlag::Temporary },
  { "OneShot", AliasFlag::OneShot }
};

static const TableEntry custom_colour[]{
  { "NoChange", -1 },       { "Custom1", 0x8080FF },  { "Custom2", 0x80FFFF },
  { "Custom3", 0x80FF80 },  { "Custom4", 0xFFFF80 },  { "Custom5", 0xFF8000 },
  { "Custom6", 0xC080FF },  { "Custom7", 0x0000FF },  { "Custom8", 0xC08000 },
  { "Custom9", 0xFF00FF },  { "Custom10", 0x404080 }, { "Custom11", 0x4080FF },
  { "Custom12", 0x808000 }, { "Custom13", 0x804000 }, { "Custom14", 0x8000FF },
  { "Custom15", 0x008000 }, { "Custom16", 0xFF0000 }, { "CustomOther", -1 }
};

static const TableEntry error_code[]{
  { "eOK", ApiCode::OK },
  { "eWorldOpen", ApiCode::WorldOpen },
  { "eWorldClosed", ApiCode::WorldClosed },
  { "eNoNameSpecified", ApiCode::NoNameSpecified },
  { "eCannotPlaySound", ApiCode::CannotPlaySound },
  { "eTriggerNotFound", ApiCode::TriggerNotFound },
  { "eTriggerAlreadyExists", ApiCode::TriggerAlreadyExists },
  { "eTriggerCannotBeEmpty", ApiCode::TriggerCannotBeEmpty },
  { "eInvalidObjectLabel", ApiCode::InvalidObjectLabel },
  { "eScriptNameNotLocated", ApiCode::ScriptNameNotLocated },
  { "eAliasNotFound", ApiCode::AliasNotFound },
  { "eAliasAlreadyExists", ApiCode::AliasAlreadyExists },
  { "eAliasCannotBeEmpty", ApiCode::AliasCannotBeEmpty },
  { "eCouldNotOpenFile", ApiCode::CouldNotOpenFile },
  { "eLogFileNotOpen", ApiCode::LogFileNotOpen },
  { "eLogFileAlreadyOpen", ApiCode::LogFileAlreadyOpen },
  { "eLogFileBadWrite", ApiCode::LogFileBadWrite },
  { "eTimerNotFound", ApiCode::TimerNotFound },
  { "eTimerAlreadyExists", ApiCode::TimerAlreadyExists },
  { "eVariableNotFound", ApiCode::VariableNotFound },
  { "eCommandNotEmpty", ApiCode::CommandNotEmpty },
  { "eBadRegularExpression", ApiCode::BadRegularExpression },
  { "eTimeInvalid", ApiCode::TimeInvalid },
  { "eBadMapItem", ApiCode::BadMapItem },
  { "eNoMapItems", ApiCode::NoMapItems },
  { "eUnknownOption", ApiCode::UnknownOption },
  { "eOptionOutOfRange", ApiCode::OptionOutOfRange },
  { "eTriggerSequenceOutOfRange", ApiCode::TriggerSequenceOutOfRange },
  { "eTriggerSendToInvalid", ApiCode::TriggerSendToInvalid },
  { "eTriggerLabelNotSpecified", ApiCode::TriggerLabelNotSpecified },
  { "ePluginFileNotFound", ApiCode::PluginFileNotFound },
  { "eProblemsLoadingPlugin", ApiCode::ProblemsLoadingPlugin },
  { "ePluginCannotSetOption", ApiCode::PluginCannotSetOption },
  { "ePluginCannotGetOption", ApiCode::PluginCannotGetOption },
  { "eNoSuchPlugin", ApiCode::NoSuchPlugin },
  { "eNotAPlugin", ApiCode::NotAPlugin },
  { "eNoSuchRoutine", ApiCode::NoSuchRoutine },
  { "ePluginDoesNotSaveState", ApiCode::PluginDoesNotSaveState },
  { "ePluginCouldNotSaveState", ApiCode::PluginCouldNotSaveState },
  { "ePluginDisabled", ApiCode::PluginDisabled },
  { "eErrorCallingPluginRoutine", ApiCode::ErrorCallingPluginRoutine },
  { "eCommandsNestedTooDeeply", ApiCode::CommandsNestedTooDeeply },
  { "eCannotCreateChatSocket", ApiCode::CannotCreateChatSocket },
  { "eCannotLookupDomainName", ApiCode::CannotLookupDomainName },
  { "eNoChatConnections", ApiCode::NoChatConnections },
  { "eChatPersonNotFound", ApiCode::ChatPersonNotFound },
  { "eBadParameter", ApiCode::BadParameter },
  { "eChatAlreadyListening", ApiCode::ChatAlreadyListening },
  { "eChatIDNotFound", ApiCode::ChatIDNotFound },
  { "eChatAlreadyConnected", ApiCode::ChatAlreadyConnected },
  { "eClipboardEmpty", ApiCode::ClipboardEmpty },
  { "eFileNotFound", ApiCode::FileNotFound },
  { "eAlreadyTransferringFile", ApiCode::AlreadyTransferringFile },
  { "eNotTransferringFile", ApiCode::NotTransferringFile },
  { "eNoSuchCommand", ApiCode::NoSuchCommand },
  { "eArrayAlreadyExists", ApiCode::ArrayAlreadyExists },
  { "eArrayDoesNotExist", ApiCode::ArrayDoesNotExist },
  { "eArrayNotEvenNumberOfValues", ApiCode::ArrayNotEvenNumberOfValues },
  { "eImportedWithDuplicates", ApiCode::ImportedWithDuplicates },
  { "eBadDelimiter", ApiCode::BadDelimiter },
  { "eSetReplacingExistingValue", ApiCode::SetReplacingExistingValue },
  { "eKeyDoesNotExist", ApiCode::KeyDoesNotExist },
  { "eCannotImport", ApiCode::CannotImport },
  { "eItemInUse", ApiCode::ItemInUse },
  { "eSpellCheckNotActive", ApiCode::SpellCheckNotActive },
  { "eCannotAddFont", ApiCode::CannotAddFont },
  { "ePenStyleNotValid", ApiCode::PenStyleNotValid },
  { "eUnableToLoadImage", ApiCode::UnableToLoadImage },
  { "eImageNotInstalled", ApiCode::ImageNotInstalled },
  { "eInvalidNumberOfPoints", ApiCode::InvalidNumberOfPoints },
  { "eInvalidPoint", ApiCode::InvalidPoint },
  { "eHotspotPluginChanged", ApiCode::HotspotPluginChanged },
  { "eHotspotNotInstalled", ApiCode::HotspotNotInstalled },
  { "eNoSuchWindow", ApiCode::NoSuchWindow },
  { "eBrushStyleNotValid", ApiCode::BrushStyleNotValid }
};

static const std::pair<ApiCode, const char*> error_desc[]{
  { ApiCode::OK, "No error" },
  { ApiCode::WorldOpen, "The world is already open" },
  { ApiCode::WorldClosed,
    "The world is closed, this action cannot be performed" },
  { ApiCode::NoNameSpecified,
    "No name has been specified where one is required" },
  { ApiCode::CannotPlaySound, "The sound file could not be played" },
  { ApiCode::TriggerNotFound, "The specified trigger name does not exist" },
  { ApiCode::TriggerAlreadyExists,
    "Attempt to add a trigger that already exists" },
  { ApiCode::TriggerCannotBeEmpty,
    "The trigger \"match\" string cannot be empty" },
  { ApiCode::InvalidObjectLabel, "The name of this object is invalid" },
  { ApiCode::ScriptNameNotLocated, "Script name is not in the script file" },
  { ApiCode::AliasNotFound, "The specified alias name does not exist" },
  { ApiCode::AliasAlreadyExists, "Attempt to add a alias that already exists" },
  { ApiCode::AliasCannotBeEmpty, "The alias \"match\" string cannot be empty" },
  { ApiCode::CouldNotOpenFile, "Unable to open requested file" },
  { ApiCode::LogFileNotOpen, "Log file was not open" },
  { ApiCode::LogFileAlreadyOpen, "Log file was already open" },
  { ApiCode::LogFileBadWrite, "Bad write to log file" },
  { ApiCode::TimerNotFound, "The specified timer name does not exist" },
  { ApiCode::TimerAlreadyExists, "Attempt to add a timer that already exists" },
  { ApiCode::VariableNotFound,
    "Attempt to delete a variable that does not exist" },
  { ApiCode::CommandNotEmpty,
    "Attempt to use SetCommand with a non-empty command window" },
  { ApiCode::BadRegularExpression, "Bad regular expression syntax" },
  { ApiCode::TimeInvalid, "Time given to AddTimer is invalid" },
  { ApiCode::BadMapItem, "Direction given to AddToMapper is invalid" },
  { ApiCode::NoMapItems, "No items in mapper" },
  { ApiCode::UnknownOption, "Option name not found" },
  { ApiCode::OptionOutOfRange, "New value for option is out of range" },
  { ApiCode::TriggerSequenceOutOfRange, "Trigger sequence value invalid" },
  { ApiCode::TriggerSendToInvalid, "Where to send trigger text to is invalid" },
  { ApiCode::TriggerLabelNotSpecified,
    "Trigger label not specified/invalid for 'send to variable'" },
  { ApiCode::PluginFileNotFound, "File name specified for plugin not found" },
  { ApiCode::ProblemsLoadingPlugin,
    "There was a parsing or other problem loading the plugin" },
  { ApiCode::PluginCannotSetOption,
    "Plugin is not allowed to set this option" },
  { ApiCode::PluginCannotGetOption,
    "Plugin is not allowed to get this option" },
  { ApiCode::NoSuchPlugin, "Requested plugin is not installed" },
  { ApiCode::NotAPlugin, "Only a plugin can do this" },
  { ApiCode::NoSuchRoutine,
    "Plugin does not support that subroutine (subroutine not in script)" },
  { ApiCode::PluginDoesNotSaveState, "Plugin does not support saving state" },
  { ApiCode::PluginCouldNotSaveState,
    "Plugin could not save state (eg. no state directory)" },
  { ApiCode::PluginDisabled, "Plugin is currently disabled" },
  { ApiCode::ErrorCallingPluginRoutine, "Could not call plugin routine" },
  { ApiCode::CommandsNestedTooDeeply,
    "Calls to \"Execute\" nested too deeply" },
  { ApiCode::CannotCreateChatSocket,
    "Unable to create socket for chat connection" },
  { ApiCode::CannotLookupDomainName,
    "Unable to do DNS (domain name) lookup for chat connection" },
  { ApiCode::NoChatConnections, "No chat connections open" },
  { ApiCode::ChatPersonNotFound, "Requested chat person not connected" },
  { ApiCode::BadParameter,
    "General problem with a parameter to a script call" },
  { ApiCode::ChatAlreadyListening, "Already listening for incoming chats" },
  { ApiCode::ChatIDNotFound, "Chat session with that ID not found" },
  { ApiCode::ChatAlreadyConnected, "Already connected to that server/port" },
  { ApiCode::ClipboardEmpty, "Cannot get (text from the) clipboard" },
  { ApiCode::FileNotFound, "Cannot open the specified file" },
  { ApiCode::AlreadyTransferringFile, "Already transferring a file" },
  { ApiCode::NotTransferringFile, "Not transferring a file" },
  { ApiCode::NoSuchCommand, "There is not a command of that name" },
  { ApiCode::ArrayAlreadyExists, "That array already exists" },
  { ApiCode::BadKeyName, "That name is not permitted for a key" },
  { ApiCode::ArrayDoesNotExist, "That array does not exist" },
  { ApiCode::ArrayNotEvenNumberOfValues,
    "Values to be imported into array are not in pairs" },
  { ApiCode::ImportedWithDuplicates,
    "Import succeeded, however some values were overwritten" },
  { ApiCode::BadDelimiter,
    "Import/export delimiter must be a single "
    "character, other than backslash" },
  { ApiCode::SetReplacingExistingValue,
    "Array element set, existing value overwritten" },
  { ApiCode::KeyDoesNotExist, "Array key does not exist" },
  { ApiCode::CannotImport,
    "Cannot import because cannot find unused temporary character" },
  { ApiCode::ItemInUse,
    "Cannot delete trigger/alias/timer because it is executing a script" },
  { ApiCode::SpellCheckNotActive, "Spell checker is not active" },
  { ApiCode::CannotAddFont, "Cannot create requested font" },
  { ApiCode::PenStyleNotValid, "Invalid settings for pen parameter" },
  { ApiCode::UnableToLoadImage, "Bitmap image could not be loaded" },
  { ApiCode::ImageNotInstalled, "Image has not been loaded into window" },
  { ApiCode::InvalidNumberOfPoints, "Number of points supplied is incorrect" },
  { ApiCode::InvalidPoint, "Point is not numeric" },
  { ApiCode::HotspotPluginChanged,
    "Hotspot processing must all be in same plugin" },
  { ApiCode::HotspotNotInstalled,
    "Hotspot has not been defined for this window" },
  { ApiCode::NoSuchWindow, "Requested miniwindow does not exist" },
  { ApiCode::BrushStyleNotValid, "Invalid settings for brush parameter" }
};

static const TableEntry miniwin[]{
  { "pos_stretch_to_view", MiniWindow::Position::OutputStretch },
  { "pos_stretch_to_view_with_aspect", MiniWindow::Position::OutputScale },
  { "pos_stretch_to_owner", MiniWindow::Position::OwnerStretch },
  { "pos_stretch_to_owner_with_aspect", MiniWindow::Position::OwnerScale },
  { "pos_top_left", MiniWindow::Position::TopLeft },
  { "pos_top_center", MiniWindow::Position::TopCenter },
  { "pos_top_right", MiniWindow::Position::TopRight },
  { "pos_center_right", MiniWindow::Position::CenterRight },
  { "pos_bottom_right", MiniWindow::Position::BottomRight },
  { "pos_bottom_center", MiniWindow::Position::BottomCenter },
  { "pos_bottom_left", MiniWindow::Position::BottomLeft },
  { "pos_center_left", MiniWindow::Position::CenterLeft },
  { "pos_center_all", MiniWindow::Position::Center },
  { "pos_tile", MiniWindow::Position::Tile },

  { "create_underneath", MiniWindow::Flag::DrawUnderneath },
  { "create_absolute_location", MiniWindow::Flag::Absolute },
  { "create_transparent", MiniWindow::Flag::Transparent },
  { "create_ignore_mouse", MiniWindow::Flag::IgnoreMouse },
  { "create_keep_hotspots", MiniWindow::Flag::KeepHotspots },

  { "pen_solid", ScriptPen::Style::SolidLine },
  { "pen_dash", ScriptPen::Style::DashLine },
  { "pen_dot", ScriptPen::Style::DotLine },
  { "pen_dash_dot", ScriptPen::Style::DashDotLine },
  { "pen_dash_dot_dot", ScriptPen::Style::DashDotDotLine },
  { "pen_null", ScriptPen::Style::NoPen },
  { "pen_inside_frame", ScriptPen::Style::InsideFrame },

  { "pen_endcap_round", ScriptPen::Cap::RoundCap },
  { "pen_endcap_square", ScriptPen::Cap::SquareCap },
  { "pen_endcap_flat", ScriptPen::Cap::FlatCap },

  { "pen_join_round", ScriptPen::Join::RoundJoin },
  { "pen_join_bevel", ScriptPen::Join::BevelJoin },
  { "pen_join_miter", ScriptPen::Join::MiterJoin },

  { "brush_solid", ScriptBrush::SolidPattern },
  { "brush_null", ScriptBrush::NoBrush },
  { "brush_hatch_horizontal", ScriptBrush::HorPattern },
  { "brush_hatch_vertical", ScriptBrush::VerPattern },
  { "brush_hatch_forwards_diagonal", ScriptBrush::FDiagPattern },
  { "brush_hatch_backwards_diagonal", ScriptBrush::BDiagPattern },
  { "brush_hatch_cross", ScriptBrush::CrossPattern },
  { "brush_hatch_cross_diagonal", ScriptBrush::DiagCrossPattern },
  { "brush_fine_pattern", ScriptBrush::Dense4Pattern },
  { "brush_medium_pattern", ScriptBrush::Dense2Pattern },
  { "brush_coarse_pattern", ScriptBrush::Dense1Pattern },
  { "brush_waves_horizontal", ScriptBrush::HorWaves },
  { "brush_waves_vertical", ScriptBrush::VerWaves },

  { "rect_frame", RectOp::Frame },
  { "rect_fill", RectOp::Fill },
  { "rect_invert", RectOp::Invert },
  { "rect_3d_rect", RectOp::Frame3D },
  { "rect_draw_edge", RectOp::Edge3D },
  { "rect_flood_fill_border", RectOp::FloodFillBorder },
  { "rect_flood_fill_surface", RectOp::FloodFillSurface },
  { "rect_edge_raised", ButtonFrame::Raised },
  { "rect_edge_etched", ButtonFrame::Etched },
  { "rect_edge_bump", ButtonFrame::Bump },
  { "rect_edge_sunken", ButtonFrame::Sunken },
  { "rect_edge_at_top_left", 0x3 },
  { "rect_edge_at_top_right", 0x6 },
  { "rect_edge_at_bottom_left", 0x9 },
  { "rect_edge_at_bottom_right", 0xC },
  { "rect_edge_at_all", 0xF },
  { "rect_diagonal_end_top_left", 0x13 },
  { "rect_diagonal_end_top_right", 0x16 },
  { "rect_diagonal_end_bottom_left", 0x19 },
  { "rect_diagonal_end_bottom_right", 0x1C },
  { "rect_option_fill_middle", MiniWindow::ButtonFlag::Fill },
  { "rect_option_softer_buttons", MiniWindow::ButtonFlag::Soft },
  { "rect_option_flat_borders", MiniWindow::ButtonFlag::Flat },
  { "rect_option_monochrom_borders", MiniWindow::ButtonFlag::Monochrome },

  { "circle_ellipse", CircleOp::Ellipse },
  { "circle_rectangle", CircleOp::Rectangle },
  { "circle_round_rectangle", CircleOp::RoundedRectangle },
  { "circle_chord", CircleOp::Chord },
  { "circle_pie", CircleOp::Pie },

  { "gradient_horizontal", Qt::Orientation::Horizontal },
  { "gradient_vertical", Qt::Orientation::Vertical },
  { "gradient_texture", 3 },

  { "font_charset_ansi", 0 },
  { "font_charset_default", 1 },
  { "font_charset_symbol", 2 },

  { "font_family_any", ScriptFont::Family::AnyFamily },
  { "font_family_roman", ScriptFont::Family::Roman },
  { "font_family_swiss", ScriptFont::Family::Swiss },
  { "font_family_modern", ScriptFont::Family::Modern },
  { "font_family_script", ScriptFont::Family::Script },
  { "font_family_decorative", ScriptFont::Family::Decorative },

  { "font_pitch_default", ScriptFont::Pitch::Default },
  { "font_pitch_fixed", ScriptFont::Pitch::Fixed },
  { "font_pitch_variable", ScriptFont::Pitch::Variable },
  { "font_pitch_monospaced", ScriptFont::Pitch::Monospace },

  { "font_truetype", 4 },

  { "image_copy", DrawImageMode::Copy },
  { "image_stretch", DrawImageMode::Stretch },
  { "image_transparent_copy", DrawImageMode::CopyTransparent },

  { "image_fill_ellipse", ImageOp::Ellipse },
  { "image_fill_rectangle", ImageOp::Rectangle },
  { "image_fill_round_fill_rectangle", ImageOp::RoundedRectangle },

  { "filter_noise", FilterOp::Noise },
  { "filter_monochrome_noise", FilterOp::MonoNoise },
  { "filter_blur", FilterOp::Blur },
  { "filter_sharpen", FilterOp::Sharpen },
  { "filter_find_edges", FilterOp::EdgeDetect },
  { "filter_emboss", FilterOp::Emboss },
  { "filter_brightness", FilterOp::BrightnessAdd },
  { "filter_contrast", FilterOp::Contrast },
  { "filter_gamma", FilterOp::Gamma },
  { "filter_red_brightness", FilterOp::RedBrightnessAdd },
  { "filter_red_contrast", FilterOp::RedContrast },
  { "filter_red_gamma", FilterOp::RedGamma },
  { "filter_green_brightness", FilterOp::GreenBrightnessAdd },
  { "filter_green_contrast", FilterOp::GreenContrast },
  { "filter_green_gamma", FilterOp::GreenGamma },
  { "filter_blue_brightness", FilterOp::BlueBrightnessAdd },
  { "filter_blue_contrast", FilterOp::BlueContrast },
  { "filter_blue_gamma", FilterOp::BlueGamma },
  { "filter_grayscale", FilterOp::GrayscaleLinear },
  { "filter_normal_grayscale", FilterOp::GrayscalePerceptual },
  { "filter_brightness_multiply", FilterOp::BrightnessMult },
  { "filter_red_brightness_multiply", FilterOp::RedBrightnessMult },
  { "filter_green_brightness_multiply", FilterOp::GreenBrightnessMult },
  { "filter_blue_brightness_multiply", FilterOp::BlueBrightnessMult },
  { "filter_lesser_blur", FilterOp::LesserBlur },
  { "filter_minor_blur", FilterOp::MinorBlur },
  { "filter_average", FilterOp::Average },

  { "blend_normal", BlendMode::Normal },
  { "blend_average", BlendMode::Average },
  { "blend_interpolate", BlendMode::Interpolate },
  { "blend_dissolve", BlendMode::Dissolve },
  { "blend_darken", BlendMode::Darken },
  { "blend_multiply", BlendMode::Multiply },
  { "blend_colour_burn", BlendMode::ColorBurn },
  { "blend_linear_burn", BlendMode::LinearBurn },
  { "blend_inverse_colour_burn", BlendMode::InverseColorBurn },
  { "blend_subtract", BlendMode::Subtract },
  { "blend_lighten", BlendMode::Lighten },
  { "blend_screen", BlendMode::Screen },
  { "blend_colour_dodge", BlendMode::ColorDodge },
  { "blend_linear_dodge", BlendMode::LinearDodge },
  { "blend_inverse_colour_dodge", BlendMode::InverseColorDodge },
  { "blend_add", BlendMode::Add },
  { "blend_overlay", BlendMode::Overlay },
  { "blend_soft_light", BlendMode::SoftLight },
  { "blend_hard_light", BlendMode::HardLight },
  { "blend_vivid_light", BlendMode::VividLight },
  { "blend_linear_light", BlendMode::LinearLight },
  { "blend_pin_light", BlendMode::PinLight },
  { "blend_hard_mix", BlendMode::HardMix },
  { "blend_difference", BlendMode::Difference },
  { "blend_exclusion", BlendMode::Exclusion },
  { "blend_reflect", BlendMode::Reflect },
  { "blend_glow", BlendMode::Glow },
  { "blend_freeze", BlendMode::Freeze },
  { "blend_heat", BlendMode::Heat },
  { "blend_negation", BlendMode::Negation },
  { "blend_phoenix", BlendMode::Phoenix },
  { "blend_stamp", BlendMode::Stamp },
  { "blend_xor", BlendMode::Xor },
  { "blend_and", BlendMode::And },
  { "blend_or", BlendMode::Or },
  { "blend_red", BlendMode::Red },
  { "blend_green", BlendMode::Green },
  { "blend_blue", BlendMode::Blue },
  { "blend_yellow", BlendMode::Yellow },
  { "blend_cyan", BlendMode::Cyan },
  { "blend_magenta", BlendMode::Magenta },
  { "blend_green_limited_by_red", BlendMode::GreenLimitedByRed },
  { "blend_green_limited_by_blue", BlendMode::GreenLimitedByBlue },
  { "blend_green_limited_by_average_of_red_and_blue",
    BlendMode::GreenLimitedByRedAndBlue },
  { "blend_blue_limited_by_red", BlendMode::BlueLimitedByRed },
  { "blend_blue_limited_by_green", BlendMode::BlueLimitedByGreen },
  { "blend_blue_limited_by_average_of_red_and_green",
    BlendMode::BlueLimitedByRedAndGreen },
  { "blend_red_limited_by_green", BlendMode::RedLimitedByGreen },
  { "blend_red_limited_by_blue", BlendMode::RedLimitedByBlue },
  { "blend_red_limited_by_average_of_green_and_blue",
    BlendMode::RedLimitedByGreenAndBlue },
  { "blend_red_only", BlendMode::RedOnly },
  { "blend_green_only", BlendMode::GreenOnly },
  { "blend_blue_only", BlendMode::BlueOnly },
  { "blend_discard_red", BlendMode::DiscardRed },
  { "blend_discard_green", BlendMode::DiscardGreen },
  { "blend_discard_blue", BlendMode::DiscardBlue },
  { "blend_all_red", BlendMode::AllRed },
  { "blend_all_green", BlendMode::AllGreen },
  { "blend_all_blue", BlendMode::AllBlue },
  { "blend_hue_mode", BlendMode::Hue },
  { "blend_saturation_mode", BlendMode::Saturation },
  { "blend_colour_mode", BlendMode::Color },
  { "blend_luminance_mode", BlendMode::Luminance },
  { "blend_hsl", BlendMode::Hsl },

  { "cursor_none", ScriptCursor::BlankCursor },
  { "cursor_arrow", ScriptCursor::ArrowCursor },
  { "cursor_hand", ScriptCursor::OpenHandCursor },
  { "cursor_ibeam", ScriptCursor::IBeamCursor },
  { "cursor_plus", ScriptCursor::CrossCursor },
  { "cursor_wait", ScriptCursor::WaitCursor },
  { "cursor_up", ScriptCursor::UpArrowCursor },
  { "cursor_nw_se_arrow", ScriptCursor::SizeFDiagCursor },
  { "cursor_ne_sw_arrow", ScriptCursor::SizeBDiagCursor },
  { "cursor_ew_arrow", ScriptCursor::SizeHorCursor },
  { "cursor_ns_arrow", ScriptCursor::SizeVerCursor },
  { "cursor_both_arrow", ScriptCursor::SizeAllCursor },
  { "cursor_x", ScriptCursor::ForbiddenCursor },
  { "cursor_help", ScriptCursor::WhatsThisCursor },

  { "hotspot_report_all_mouseovers", Hotspot::Flag::ReportAllMouseovers },

  { "hotspot_got_shift", Hotspot::EventFlag::Shift },
  { "hotspot_got_control", Hotspot::EventFlag::Control },
  { "hotspot_got_alt", Hotspot::EventFlag::Alt },
  { "hotspot_got_lh_mouse", Hotspot::EventFlag::MouseLeft },
  { "hotspot_got_rh_mouse", Hotspot::EventFlag::MouseRight },
  { "hotspot_got_dbl_click", Hotspot::EventFlag::DoubleClick },
  { "hotspot_got_not_first", Hotspot::EventFlag::Hover },
  { "hotspot_got_middle_mouse", Hotspot::EventFlag::MouseMiddle },

  { "merge_straight", MergeMode::Straight },
  { "merge_transparent", MergeMode::Transparent },

  { "drag_got_shift", Hotspot::EventFlag::Shift },
  { "drag_got_control", Hotspot::EventFlag::Control },
  { "drag_got_alt", Hotspot::EventFlag::Alt },

  { "wheel_got_shift", Hotspot::EventFlag::Shift },
  { "wheel_got_control", Hotspot::EventFlag::Control },
  { "wheel_got_alt", Hotspot::EventFlag::Alt },
  { "wheel_scroll_back", Hotspot::EventFlag::ScrollDown }
};

static const TableEntry operating_system[]{
  { "Windows", OperatingSystem::Windows },
  { "MacOS", OperatingSystem::MacOS },
  { "Linux", OperatingSystem::Linux }
};

static const TableEntry sendto[]{
  { "world", SendTarget::World },
  { "command", SendTarget::Command },
  { "output", SendTarget::Output },
  { "status", SendTarget::Status },
  { "notepad", SendTarget::NotepadNew },
  { "notepadappend", SendTarget::NotepadAppend },
  { "logfile", SendTarget::Log },
  { "notepadreplace", SendTarget::NotepadReplace },
  { "commandqueue", SendTarget::WorldDelay },
  { "variable", SendTarget::Variable },
  { "execute", SendTarget::Execute },
  { "speedwalk", SendTarget::Speedwalk },
  { "script", SendTarget::Script },
  { "immediate", SendTarget::WorldImmediate },
  { "scriptafteromit", SendTarget::ScriptAfterOmit }
};

static const TableEntry timer_flag[]{
  { "Enabled", TimerFlag::Enabled },
  { "AtTime", TimerFlag::AtTime },
  { "OneShot", TimerFlag::OneShot },
  { "TimerSpeedwalk", TimerFlag::TimerSpeedWalk },
  { "TimerNote", TimerFlag::TimerNote },
  { "ActiveWhenClosed", TimerFlag::ActiveWhenClosed },
  { "Replace", TimerFlag::Replace },
  { "Temporary", TimerFlag::Temporary }
};

static const TableEntry trigger_flag[]{
  { "Enabled", TriggerFlag::Enabled },
  { "OmitFromLog", TriggerFlag::OmitFromLog },
  { "OmitFromOutput", TriggerFlag::OmitFromOutput },
  { "KeepEvaluating", TriggerFlag::KeepEvaluating },
  { "IgnoreCase", TriggerFlag::IgnoreCase },
  { "RegularExpression", TriggerFlag::RegularExpression },
  { "ExpandVariables", TriggerFlag::ExpandVariables },
  { "Replace", TriggerFlag::Replace },
  { "LowercaseWildcard", TriggerFlag::LowercaseWildcard },
  { "Temporary", TriggerFlag::Temporary },
  { "OneShot", TriggerFlag::OneShot }
};

namespace {
template<typename T>
void
registerTable(lua_State* L, const char* name, const T& entries)
{
  qlua::pushMap(L, entries);
  lua_setglobal(L, name);
}
} // namespace

int
luaopen_smushglobals(lua_State* L)
{
  qlua::push(L, QCoreApplication::applicationVersion());
  lua_setglobal(L, "SMUSHCLIENT_VERSION");
  registerTable(L, "alias_flag", alias_flag);
  registerTable(L, "custom_colour", custom_colour);
  registerTable(L, "error_code", error_code);
  registerTable(L, "error_desc", error_desc);
  registerTable(L, "miniwin", miniwin);
  registerTable(L, "operating_system", operating_system);
  registerTable(L, "sendto", sendto);
  registerTable(L, "timer_flag", timer_flag);
  registerTable(L, "trigger_flag", trigger_flag);
  return 0;
}
